
addpath matlab
addpath examples


vl_compilenn('enableGpu', true, ...
               'cudaRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0', ...
               'cudaMethod', 'nvcc', ...
               'enableCudnn', true, ...
               'cudnnRoot', 'C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\cuda') ;